sudo: required
dist: trusty
language: c
before_install:
  - source remove_translation_packages.sh 
  - sudo apt-get install -y git
  - source zsh/install_git_and_zsh.sh
install: 
  - ./setup_science_stack.zsh
script: echo "Done provisioning."
