sudo: required
dist: trusty
language: c
install: 
  - make .zsh.ind .nvim.ind .full_R.ind
script: 
  - source ~/.zshrc || echo ""
  - which nvim
  - which python | grep 'anaconda'
  - which R | grep 'anaconda'
