sudo: required
language: c
install: 
  - sudo sh remove_translation_packages.sh 
  - sudo sh misc/install_jdk_and_postgres_driver.sh
  - sudo sh zsh/install_git_and_zsh.sh
  - sudo sh vim/install_gvim_and_plugins.sh
  - sudo sh R/update_ubuntu_R_repo.sh
  - sudo sh R/install_R_package_dependencies.sh 
  - sudo sh tmux/install_tmux_and_plugins.sh 
script: Rscript -e 'cat(0)'
